FROM node:20-alpine

WORKDIR /app

# Copy client files
COPY client/package*.json ./
COPY client/ ./

# Install dependencies
RUN npm install

# Build
RUN npm run build

ENV NODE_ENV=production

# Next.js runs on port 3000 by default
ENV PORT=3000

EXPOSE 3000

# Start Next.js
CMD ["npm", "run", "start"]
